system:
  wake_word:
    - "Hey, amigo"
    - "hey amigo"
    - "hey amiga"
    - "hey, amiga"
  device_id: "nexa_spot_01"

lm_studio:
  base_url: "http://localhost:1234/v1"
  model: "llama-3.2-3b-instruct"
  temperature: 0.4
  max_tokens: 400

piper_tts:
  model_path: 'your_path_to_tts_model.onnx'
  config_path: 'your_path_to_tts_model_config.json'
  speaker_id: 0

mqtt:
  broker: "localhost"
  port: 1883
  topic_prefix: "nexa/spot"
